test: github integration
* test: up coverage

* test: try failing test

* test: jest reporter

* test: fix tests again

* test: failing

* test: merge-ready

* test: failing

* test: merge-ready

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,6 @@
 # Deploy to github pages
 
-name: Publish Pages
+name: Main Workflow
 
 # Controls when the workflow will run
 on:
@@ -24,11 +24,26 @@ jobs:
                   cache: "npm"
                   cache-dependency-path: ./package-lock.json
             - name: Run NPM tests
+              continue-on-error: true
               run: npm run install-test
-            - uses: 5monkeys/cobertura-action@master
+            - name: Process jest results
+              id: process-jest
+              if: always()
+              uses: im-open/process-jest-test-results@v2.1
+              with:
+                  github-token: ${{ secrets.GITHUB_TOKEN }}
+                  results-file: "coverage/jest-results.json"
+            - name: Process coverage
+              uses: 5monkeys/cobertura-action@master
+              if: always()
               with:
                   path: coverage/cobertura-coverage.xml
-                  minimum_coverage: 20
+                  minimum_coverage: 90
+            - name: Fail if there were errors in the jest tests
+              if: steps.process-jest.outputs.test-outcome == 'Failed'
+              run: |
+                  echo "There were test failures."
+                  exit 1
     build:
         runs-on: ubuntu-latest
         needs: test
